### ISSUE TITLE
List of commits should show user's commits

### ISSUE THREAD

**Issue by dhatanian** [TobyRet/Checkin#1]
Steps to reproduce:

- Log in
- Check in
- Click on the `Add commits` button

Expected result:
The user sees the commits they did yesterday (or Friday for Monday) across all the repositories they contribute to.

Actual result:
The user sees a list of commits from another repo (I guess this repo)

![image](https://cloud.githubusercontent.com/assets/1684420/23794581/b7cd0b94-0588-11e7-8284-7299cd803f29.png)

**Comment by TobyTestDummy** [comment]
Thanks for raising @dhatanian 
Fix is now live

**Comment by TobyRet** [comment]
Thanks for raising @dhatanian
Fix is now live
